server {
    listen 443 ssl;
    server_name grafana.minstudio.app;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    ssl_certificate /etc/letsencrypt/live/grafana.minstudio.app/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/grafana.minstudio.app/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    location / {
        resolver 127.0.0.11 valid=30s;
        set $upstream http://port_grafana:3000;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
