server {
    listen 80;
    server_name shop.minstudio.app;

    # Let's Encrypt 챌린지를 위한 경로
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # HTTP 요청을 HTTPS로 리다이렉트 (HTTPS가 적용될 경우 주석 해제)
    location / {
        return 301 https://$host$request_uri;
    }
}
